@Library('blackduck-logs-publisher') _

pipeline {
    agent { label 'mac-sh' }

    stages {
        stage("Build") {
            steps {
                script {
                    echo "JOB_NAME: ${env.JOB_NAME}"

                    dir('nodejs-npm') {
                        sh 'node --version'
                        sh 'npm --version'
                        sh 'npm install'
                    }
                }
            }
        }

        stage("polaris-detailed-workflow") {
            when {
                
                anyOf {
                    branch 'main'
                    branch pattern: "PR-\\d+", comparator: "REGEXP"
                }
            }
            steps {
                script {
                    dir('nodejs-npm') {
                        security_scan coverity_build_command: 'npm install', coverity_clean_command: 'npm cache clean --force', coverity_prComment_enabled: true,
                          coverity_prComment_impacts: 'HIGH, MEDIUM', coverity_waitForScan: true, mark_build_status: 'SUCCESS', product: 'coverity'

                    }
                    
                   
                }
            }
        }
        

      
    }

    post {
        always {
            pushJenkinsLogsToGitHub([
                githubOrg: 'coverity-cnc-jenkins-samples',
                repoName: 'detailed-example',
                retentionCount: 5
            ])
        }
    }
}



